# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 80, host: 8090

  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder "~/Daniel/fucky/site", "/var/www", create:true
  config.vm.provision :shell, :path => "ubuntu-provision.sh"
end